# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import sys
import platform
import register
import user
import apply
import display
import psycopg2
import myparticipation
import myapply
import comment


class Ui_login(object):

    def setupUi(self, login):
        #为退出按钮做准备
        self.window = login

        login.setObjectName("login")
        login.resize(842, 512)
        login.setMinimumSize(QtCore.QSize(842, 512))
        login.setMaximumSize(QtCore.QSize(842, 512))

        self.LoginButton = QtWidgets.QPushButton(login)
        self.LoginButton.setGeometry(QtCore.QRect(180, 360, 93, 28))
        self.LoginButton.setObjectName("LoginButton")
        self.QuitButton = QtWidgets.QPushButton(login)
        self.QuitButton.setGeometry(QtCore.QRect(370, 360, 93, 28))
        self.QuitButton.setObjectName("QuitButton")
        self.WESALON = QtWidgets.QLabel(login)
        self.WESALON.setGeometry(QtCore.QRect(240, 50, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.WESALON.setFont(font)
        self.WESALON.setObjectName("WESALON")
        self.IDLabel = QtWidgets.QLabel(login)
        self.IDLabel.setGeometry(QtCore.QRect(100, 180, 72, 15))
        self.IDLabel.setObjectName("IDLabel")
        self.PasswordLabel = QtWidgets.QLabel(login)
        self.PasswordLabel.setGeometry(QtCore.QRect(70, 260, 72, 15))
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.LoginMessage = QtWidgets.QTextBrowser(login)
        self.LoginMessage.setGeometry(QtCore.QRect(490, 130, 256, 192))
        self.LoginMessage.setObjectName("LoginMessage")
        self.IDEdit = QtWidgets.QLineEdit(login)
        self.IDEdit.setGeometry(QtCore.QRect(180, 180, 113, 21))
        self.IDEdit.setObjectName("IDEdit")
        self.PasswordEdit = QtWidgets.QLineEdit(login)
        self.PasswordEdit.setGeometry(QtCore.QRect(180, 260, 113, 21))
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.RegisterButton = QtWidgets.QPushButton(login)
        self.RegisterButton.setGeometry(QtCore.QRect(330, 180, 93, 28))
        self.RegisterButton.setObjectName("RegisterButton")


        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

        # 设置密码隐藏
        self.PasswordEdit.setEchoMode(QLineEdit.Password)
        # 设置对输入内容的删除提示
        self.PasswordEdit.setClearButtonEnabled(True)
        self.IDEdit.setClearButtonEnabled(True)

        # 添加登录按钮信号和槽。调用display函数
        self.LoginButton.clicked.connect(self.display)
        # 添加退出按钮信号和槽。调用close函数
        self.QuitButton.clicked.connect(self.window.close)

        # 添加注册按钮信号和槽。调用JumpToRegister函数
        self.RegisterButton.clicked.connect(self.JumpToRegister)


    def display(self):
        # 利用line Edit控件对象text()函数获取界面输入
        userid = self.IDEdit.text()
        password = self.PasswordEdit.text()

        if userid == "" or password == "":
            self.LoginMessage.setText("账号密码不能为空，请输入！")
            return

        try:
            conn = psycopg2.connect(
                user = 'postgres',
                password = 'patrick+',
                host = '127.0.0.1',
                database = 'postgres',
                port = 5432
            )
            cursor = conn.cursor()
            query = "SELECT STU_ID, STU_PASSWORD FROM STUDENT"
            cursor.execute(query)
            for row in cursor:
                if row[0] == userid and row[1] == password:
                    # 利用text Browser控件对象setText()函数设置界面显示
                    self.LoginMessage.setText("登录成功!\n" + "用户名是: " + userid + ",密码是： " + password)
                    #将输入的ID传输给platform窗口的username变量
                    platform.username = self.IDEdit.text()
                    user.user_signal = self.IDEdit.text()
                    apply.apply_signal = self.IDEdit.text()
                    display.display_signal = self.IDEdit.text()
                    myparticipation.user_id = self.IDEdit.text()
                    myapply.user_id = self.IDEdit.text()
                    comment.user_id = self.IDEdit.text()
                    self.JumpToPlatform()
                    return
            self.LoginMessage.setText("账户或密码错误，请重新输入！")
            return

        except psycopg2.Error as err:
            print(err)
        else:
            conn.close()




    def JumpToPlatform(self):
        #self.form.hide()
        self.window.close()
        form1 = QtWidgets.QDialog()
        self.ui = platform.Ui_Platform()
        self.ui.setupUi(form1)
        form1.show()
        form1.exec_()
        #self.form.show()

    def JumpToRegister(self):
        #self.form.hide()
        form1 = QtWidgets.QDialog()
        self.ui = register.Ui_register_3()
        self.ui.setupUi(form1)
        form1.show()
        form1.exec_()
        #self.form.show()

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Login"))
        self.LoginButton.setText(_translate("login", "登录"))
        self.QuitButton.setText(_translate("login", "退出"))
        self.WESALON.setText(_translate("login", "WESALON"))
        self.IDLabel.setText(_translate("login", "ID"))
        self.PasswordLabel.setText(_translate("login", "Password"))
        self.RegisterButton.setText(_translate("login", "注册"))

if __name__ == "__main__":
     app = QApplication(sys.argv)
     form = QtWidgets.QWidget()
     window = Ui_login()
     window.setupUi(form)
     form.show()
     sys.exit(app.exec_())