# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myapply.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import psycopg2
import sys
import datetime
user_id = ""


class Ui_myapply(object):
    def setupUi(self, myapply):
        myapply.setObjectName("myapply")
        myapply.resize(1000, 680)
        myapply.setMinimumSize(QtCore.QSize(1000, 680))
        myapply.setMaximumSize(QtCore.QSize(1000, 680))
        self.MyAppliedWESALON = QtWidgets.QLabel(myapply)
        self.MyAppliedWESALON.setGeometry(QtCore.QRect(340, 10, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.MyAppliedWESALON.setFont(font)
        self.MyAppliedWESALON.setObjectName("MyAppliedWESALON")
        self.ApplyTable = QtWidgets.QTableWidget(myapply)
        self.ApplyTable.setGeometry(QtCore.QRect(60, 130, 881, 441))
        self.ApplyTable.setObjectName("ApplyTable")
        self.ApplyTable.setColumnCount(9)
        self.ApplyTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ApplyTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ApplyTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ApplyTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ApplyTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ApplyTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ApplyTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ApplyTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ApplyTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.ApplyTable.setHorizontalHeaderItem(8, item)
        self.CancelButton = QtWidgets.QPushButton(myapply)
        self.CancelButton.setGeometry(QtCore.QRect(120, 600, 93, 28))
        self.CancelButton.setObjectName("CancelButton")
        self.FlushButton = QtWidgets.QPushButton(myapply)
        self.FlushButton.setGeometry(QtCore.QRect(810, 600, 93, 28))
        self.FlushButton.setObjectName("FlushButton")
        self.CancelButton.clicked.connect(self.CancelAct)
        self.FlushButton.clicked.connect(self.LoadTable)
        self.ApplyTable.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.ApplyTable.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.retranslateUi(myapply)
        QtCore.QMetaObject.connectSlotsByName(myapply)

    def retranslateUi(self, myapply):
        _translate = QtCore.QCoreApplication.translate
        myapply.setWindowTitle(_translate("myapply", "Form"))
        self.MyAppliedWESALON.setText(_translate("myapply", "我申请的WESALON"))
        item = self.ApplyTable.horizontalHeaderItem(0)
        item.setText(_translate("myapply", "活动ID"))
        item = self.ApplyTable.horizontalHeaderItem(1)
        item.setText(_translate("myapply", "活动名字"))
        item = self.ApplyTable.horizontalHeaderItem(2)
        item.setText(_translate("myapply", "举办人"))
        item = self.ApplyTable.horizontalHeaderItem(3)
        item.setText(_translate("myapply", "开始时间"))
        item = self.ApplyTable.horizontalHeaderItem(4)
        item.setText(_translate("myapply", "结束时间"))
        item = self.ApplyTable.horizontalHeaderItem(5)
        item.setText(_translate("myapply", "活动地点"))
        item = self.ApplyTable.horizontalHeaderItem(6)
        item.setText(_translate("myapply", "活动容量"))
        item = self.ApplyTable.horizontalHeaderItem(7)
        item.setText(_translate("myapply", "已加入人数"))
        item = self.ApplyTable.horizontalHeaderItem(8)
        item.setText(_translate("myapply", "活动状态"))
        self.CancelButton.setText(_translate("myapply", "取消活动"))
        self.FlushButton.setText(_translate("myapply", "刷新"))

    def CancelAct(self):
        if self.ApplyTable.item(0, 0) == None:
            return
        row = self.ApplyTable.currentRow()
        newstu = user_id
        newact = self.ApplyTable.item(row, 0).text()
        newstart = self.ApplyTable.item(row, 3).text()
        newend = self.ApplyTable.item(row, 4).text()
        oldcurrent = self.ApplyTable.item(row, 7).text()

        try:
            print("into try")
            conn = psycopg2.connect(
                user='postgres',
                password='patrick+',
                host='127.0.0.1',
                database='postgres',
                port=5432
            )
            cursor = conn.cursor()
             
            query2 = "DELETE FROM ACTIVITY WHERE ACT_ID = %s"
            cursor.execute(query2, (newact, ))
            conn.commit()
            self.LoadTable()

        except psycopg2.Error as err:
            print("We have a problem")
            print(err)
        else:
            conn.close()

    def LoadTable(self):
        nowtime1 = datetime.datetime.now()
        try:
            conn = psycopg2.connect(
                user = 'postgres',
                password = 'patrick+',
                host = '127.0.0.1',
                database = 'postgres',
                port = 5432
            )
            cursor = conn.cursor()
            query = "SELECT * FROM ACTIVITY WHERE STU_ID = %s"
            cursor.execute(query, (user_id, ))
            rows = cursor.fetchall()
            row = cursor.rowcount  # 取得记录个数，用于设置表格的行数
            self.ApplyTable.setRowCount(row)
            if row == 0:
                return
            vol = len(rows[0])  # 取得字段数，用于设置表格的列数

            

            for i in range(row):
                for j in range(vol):
                    temp_data = rows[i][j]  # 临时记录，不能直接插入表格
                    data = QTableWidgetItem(str(temp_data))  # 转换后可插入表格
                    self.ApplyTable.setItem(i, j, data)

                if rows[i][3] > nowtime1:
                    self.ApplyTable.setItem(i, 8, QTableWidgetItem(str("reserved")))
                elif rows[i][4] < nowtime1:
                    self.ApplyTable.setItem(i, 8, QTableWidgetItem(str("finished")))
                else:
                    self.ApplyTable.setItem(i, 8, QTableWidgetItem(str("ongoing")))


        except psycopg2.Error as err:
            print(err)
        else:
            conn.close()