# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mywesalon.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QCoreApplication
import sys
import myapply
import myparticipation


class Ui_mywesalon(object):
    def setupUi(self, mywesalon):
        mywesalon.setObjectName("mywesalon")
        mywesalon.resize(1000, 600)
        mywesalon.setMinimumSize(QtCore.QSize(1000, 600))
        mywesalon.setMaximumSize(QtCore.QSize(1000, 600))
        self.MyWESALON = QtWidgets.QLabel(mywesalon)
        self.MyWESALON.setGeometry(QtCore.QRect(360, 40, 391, 111))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.MyWESALON.setFont(font)
        self.MyWESALON.setObjectName("MyWESALON")
        self.MyApply = QtWidgets.QPushButton(mywesalon)
        self.MyApply.setGeometry(QtCore.QRect(170, 280, 201, 141))
        self.MyApply.setObjectName("MyApply")
        self.MyParticipation = QtWidgets.QPushButton(mywesalon)
        self.MyParticipation.setGeometry(QtCore.QRect(630, 280, 211, 141))
        self.MyParticipation.setObjectName("MyParticipation")

        self.retranslateUi(mywesalon)
        QtCore.QMetaObject.connectSlotsByName(mywesalon)

        # 添加我申请的按钮信号和槽
        self.MyApply.clicked.connect(self.GoToMyApply)
        # 添加我参加的按钮信号和槽
        self.MyParticipation.clicked.connect(self.GoToMyParticipation)

    def GoToMyApply(self):
        form4 = QtWidgets.QDialog()
        self.ui = myapply.Ui_myapply()
        self.ui.setupUi(form4)
        form4.show()
        form4.exec_()

    def GoToMyParticipation(self):
        form5 = QtWidgets.QDialog()
        self.ui = myparticipation.Ui_myparticipation()
        self.ui.setupUi(form5)
        form5.show()
        form5.exec_()

    def retranslateUi(self, mywesalon):
        _translate = QtCore.QCoreApplication.translate
        mywesalon.setWindowTitle(_translate("mywesalon", "我的WESALON"))
        self.MyWESALON.setText(_translate("mywesalon", "我的WESALON"))
        self.MyApply.setText(_translate("mywesalon", "我申请的"))
        self.MyParticipation.setText(_translate("mywesalon", "我参加的"))

if __name__ == "__main__":
     app = QApplication(sys.argv)
     form = QtWidgets.QWidget()
     window = Ui_mywesalon()
     window.setupUi(form)
     form.show()
     sys.exit(app.exec_())