# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'platform.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QCoreApplication
import sys
import login
import user
import display
import comment
import mywesalon


#定义左上角Label的变量
username = "abc"
class Ui_Platform(object):
    def setupUi(self, Platform):
        self.window = Platform

        Platform.setObjectName("Platform")
        Platform.resize(1000, 600)
        Platform.setMinimumSize(QtCore.QSize(1000, 600))
        Platform.setMaximumSize(QtCore.QSize(1000, 600))
        self.WESALON = QtWidgets.QLabel(Platform)
        self.WESALON.setGeometry(QtCore.QRect(390, 10, 261, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.WESALON.setFont(font)
        self.WESALON.setObjectName("WESALON")
        self.UserMessage = QtWidgets.QPushButton(Platform)
        self.UserMessage.setGeometry(QtCore.QRect(380, 190, 221, 61))
        self.UserMessage.setObjectName("UserMessage")
        self.AllWESALON = QtWidgets.QPushButton(Platform)
        self.AllWESALON.setGeometry(QtCore.QRect(380, 290, 221, 61))
        self.AllWESALON.setObjectName("AllWESALON")
        self.Comments = QtWidgets.QPushButton(Platform)
        self.Comments.setGeometry(QtCore.QRect(380, 390, 221, 61))
        self.Comments.setObjectName("Comments")
        self.MyWESALON = QtWidgets.QPushButton(Platform)
        self.MyWESALON.setGeometry(QtCore.QRect(380, 490, 221, 61))
        self.MyWESALON.setObjectName("MyWESALON")
        self.BackToLogin = QtWidgets.QPushButton(Platform)
        self.BackToLogin.setGeometry(QtCore.QRect(850, 500, 93, 28))
        self.BackToLogin.setObjectName("BackToLogin")
        self.label = QtWidgets.QLabel(Platform)
        self.label.setGeometry(QtCore.QRect(30, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Platform)
        QtCore.QMetaObject.connectSlotsByName(Platform)

        # 添加用户信息按钮信号和槽
        self.UserMessage.clicked.connect(self.GoToUser)
        # 添加所有WESALON按钮信号和槽
        self.AllWESALON.clicked.connect(self.GoToDisplay)
        # 添加评论天地按钮信号和槽
        self.Comments.clicked.connect(self.GoToComment)
        # 添加我的WESALON按钮信号和槽
        self.MyWESALON.clicked.connect(self.GoToMine)
        # 添加更换用户按钮信号和槽
        self.BackToLogin.clicked.connect(self.GoToLogin)

        #改变左上角Label的名字
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Platform", username))

    def GoToUser(self):
        form1 = QtWidgets.QDialog()
        self.ui = user.Ui_user()
        self.ui.setupUi(form1)
        form1.show()
        form1.exec_()

    def GoToDisplay(self):
        form2 = QtWidgets.QDialog()
        self.ui = display.Ui_display()
        self.ui.setupUi(form2)
        form2.show()
        form2.exec_()

    def GoToComment(self):
        form3 = QtWidgets.QDialog()
        self.ui = comment.Ui_comment()
        self.ui.setupUi(form3)
        form3.show()
        form3.exec_()

    def GoToMine(self):
        form4 = QtWidgets.QDialog()
        self.ui = mywesalon.Ui_mywesalon()
        self.ui.setupUi(form4)
        form4.show()
        form4.exec_()

    def GoToLogin(self):
        #在打开下一个窗口的同时关闭本窗口
        self.window.close()
        form5 = QtWidgets.QDialog()
        self.ui = login.Ui_login()
        self.ui.setupUi(form5)
        form5.show()
        form5.exec_()


    def retranslateUi(self, Platform):
        _translate = QtCore.QCoreApplication.translate
        Platform.setWindowTitle(_translate("Platform", "Menu"))
        self.WESALON.setText(_translate("Platform", "WESALON"))
        self.UserMessage.setText(_translate("Platform", "用户信息"))
        self.AllWESALON.setText(_translate("Platform", "所有WESALON"))
        self.Comments.setText(_translate("Platform", "评论天地"))
        self.MyWESALON.setText(_translate("Platform", "我的WESALON"))
        self.BackToLogin.setText(_translate("Platform", "更换用户"))
        self.label.setText(_translate("Platform", "TextLabel"))

if __name__ == "__main__":
     app = QApplication(sys.argv)
     form = QtWidgets.QWidget()
     window = Ui_Platform()
     window.setupUi(form)
     form.show()
     sys.exit(app.exec_())