# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QCoreApplication
import sys
import psycopg2

class Ui_register_3(object):
    def setupUi(self, register_3):
        register_3.setObjectName("register_3")
        register_3.resize(842, 512)
        register_3.setMinimumSize(QtCore.QSize(842, 512))
        register_3.setMaximumSize(QtCore.QSize(842, 512))
        self.WESALON = QtWidgets.QLabel(register_3)
        self.WESALON.setGeometry(QtCore.QRect(200, 30, 411, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.WESALON.setFont(font)
        self.WESALON.setObjectName("WESALON")
        self.NameLabel = QtWidgets.QLabel(register_3)
        self.NameLabel.setGeometry(QtCore.QRect(50, 150, 121, 31))
        self.NameLabel.setObjectName("NameLabel")
        self.IDLabel = QtWidgets.QLabel(register_3)
        self.IDLabel.setGeometry(QtCore.QRect(80, 220, 72, 31))
        self.IDLabel.setObjectName("IDLabel")
        self.PasswordLabel = QtWidgets.QLabel(register_3)
        self.PasswordLabel.setGeometry(QtCore.QRect(50, 300, 151, 20))
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.AgainLabel = QtWidgets.QLabel(register_3)
        self.AgainLabel.setGeometry(QtCore.QRect(80, 360, 72, 31))
        self.AgainLabel.setObjectName("AgainLabel")
        self.NameEdit = QtWidgets.QLineEdit(register_3)
        self.NameEdit.setGeometry(QtCore.QRect(200, 150, 221, 31))
        self.NameEdit.setObjectName("NameEdit")
        self.IDEdit = QtWidgets.QLineEdit(register_3)
        self.IDEdit.setGeometry(QtCore.QRect(200, 220, 221, 31))
        self.IDEdit.setObjectName("IDEdit")
        self.PasswordEdit = QtWidgets.QLineEdit(register_3)
        self.PasswordEdit.setGeometry(QtCore.QRect(200, 290, 221, 31))
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.AgainEdit = QtWidgets.QLineEdit(register_3)
        self.AgainEdit.setGeometry(QtCore.QRect(200, 360, 221, 31))
        self.AgainEdit.setObjectName("AgainEdit")
        self.RegisterButton = QtWidgets.QPushButton(register_3)
        self.RegisterButton.setGeometry(QtCore.QRect(250, 450, 93, 28))
        self.RegisterButton.setObjectName("RegisterButton")
        self.RegisterMessage = QtWidgets.QTextBrowser(register_3)
        self.RegisterMessage.setGeometry(QtCore.QRect(510, 170, 256, 192))
        self.RegisterMessage.setObjectName("RegisterMessage")
        self.tip = QtWidgets.QLabel(register_3)
        self.tip.setGeometry(QtCore.QRect(50, 250, 141, 20))
        self.tip.setObjectName("tip")

        self.retranslateUi(register_3)
        QtCore.QMetaObject.connectSlotsByName(register_3)

        # 设置对输入内容的删除提示
        self.PasswordEdit.setClearButtonEnabled(True)
        self.IDEdit.setClearButtonEnabled(True)
        self.NameEdit.setClearButtonEnabled(True)
        self.AgainEdit.setClearButtonEnabled(True)

        # 添加登录按钮信号和槽
        self.RegisterButton.clicked.connect(self.RegisterNew)

    def RegisterNew(self):
        newid = self.IDEdit.text()
        newpassword = self.PasswordEdit.text()
        newname = self.NameEdit.text()
        again = self.AgainEdit.text()

        if newid == "" or newpassword == "" or newname == "" or again == "":
            self.RegisterMessage.setText("您有未填入的项，请重新输入！")
            return

        elif len(newid) != 10 or len(newpassword) >= 13 or len(newname) >= 13:
            self.RegisterMessage.setText("填入项长度不符合要求，请重新输入！")
            return

        elif again != newpassword:
            self.RegisterMessage.setText("两次密码输入不一致，请重新输入！")
            return

        try:
            conn = psycopg2.connect(
                user = 'postgres',
                password = 'patrick+',
                host = '127.0.0.1',
                database = 'postgres',
                port = 5432
            )
            cursor = conn.cursor()
            query1 = "SELECT STU_ID FROM STUDENT"
            cursor.execute(query1)
            for row in cursor:
                if row[0] == newid:
                    # 利用text Browser控件对象setText()函数设置界面显示
                    self.RegisterMessage.setText("此ID已被注册，请更换ID")
                    return

            query2 = "INSERT INTO STUDENT (STU_ID, STU_NAME, STU_PASSWORD) VALUES (%s, %s, %s)"
            cursor.execute(query2, (newid, newname, newpassword))
            conn.commit()
            self.RegisterMessage.setText("注册成功！")
            return
        except psycopg2.Error as err:
            print(err)
        else:
            conn.close()


    def retranslateUi(self, register_3):
        _translate = QtCore.QCoreApplication.translate
        register_3.setWindowTitle(_translate("register_3", "Register"))
        self.WESALON.setText(_translate("register_3", "欢迎加入WESALON"))
        self.NameLabel.setText(_translate("register_3", "Name(1~12个字符)"))
        self.IDLabel.setText(_translate("register_3", "ID(10位)"))
        self.PasswordLabel.setText(_translate("register_3", "Password(12位以内)"))
        self.AgainLabel.setText(_translate("register_3", "确认密码"))
        self.RegisterButton.setText(_translate("register_3", "注册"))
        self.tip.setText(_translate("register_3", "(ID请勿与他人重复)"))


if __name__ == "__main__":
     app = QApplication(sys.argv)
     form = QtWidgets.QWidget()
     window = Ui_register_3()
     window.setupUi(form)
     form.show()
     sys.exit(app.exec_())